"""not_nullabe_level_field

Revision ID: b21176e3f8ec
Revises: 9851234371a3
Create Date: 2025-01-29 12:21:55.454007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b21176e3f8ec'
down_revision: Union[str, None] = '9851234371a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'level',
               existing_type=mysql.ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'level',
               existing_type=mysql.ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED'),
               nullable=True)
    # ### end Alembic commands ###
