"""rebuild_user_model

Revision ID: cb10e697344c
Revises: a8c2204c1c59
Create Date: 2025-01-28 14:25:12.576023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cb10e697344c'
down_revision: Union[str, None] = 'a8c2204c1c59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', mysql.ENUM('ADMIN', 'ASTRONOMER', 'USER'), nullable=False))
    # ### end Alembic commands ###
