services:
  traefik:
    image: traefik:v2.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker/traefik/config:/etc/traefik
      - ./docker/traefik/dynamic:/etc/traefik/dynamic
    ports:
      - "8085:8085"  # Au lieu de 80:80
      - "8081:8080"
    labels:
      - "traefik.enable=true"
    networks:
      - traefik_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: "65534:65534"
    volumes:
      - ./docker/prometheus:/etc/prometheus:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.stellarstudio.fassih.ch`)"
      - "traefik.http.routers.prometheus.entrypoints=web"
    depends_on:
      - backend
    env_file:
      - .env
    networks:
      - traefik_network

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
      - ./docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./docker/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.stellarstudio.fassih.ch`)"
      - "traefik.http.routers.grafana.entrypoints=web"
    depends_on:
      - prometheus
    env_file:
      - .env
    networks:
      - traefik_network

  backend:
    build: ./backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.stellarstudio.fassih.ch`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
    volumes:
      - ./backend:/app
      - ./tmp:/app/tmp
    user: "1030:100"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      database:
        condition: service_healthy
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - traefik_network

  celery-download:
    build:
      context: ./backend
      dockerfile: Dockerfile.celery
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app
      - ./tmp:/app/tmp
    env_file:
      - .env
    command: celery -A app.core.celery worker -Q download_queue -n download@%h --loglevel=info
    depends_on:
      redis:
        condition: service_healthy
      database:
        condition: service_healthy
    deploy:
      mode: replicated
      replicas: 4
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "celery", "-A", "app.core.celery", "inspect", "ping", "-d", "celery@%h"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - traefik_network

  celery-processing:
    build:
      context: ./backend
      dockerfile: Dockerfile.celery
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app
      - ./tmp:/app/tmp
    env_file:
      - .env
    command: celery -A app.core.celery worker -Q processing_queue -n processing@%h --loglevel=info
    depends_on:
      redis:
        condition: service_healthy
      database:
        condition: service_healthy
    deploy:
      mode: replicated
      replicas: 4
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "celery", "-A", "app.core.celery", "inspect", "ping", "-d", "celery@%h"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - traefik_network

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
    volumes:
      - minio-data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio.rule=Host(`minio.stellarstudio.fassih.ch`)"
      - "traefik.http.routers.minio.entrypoints=web"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    networks:
      - traefik_network

  frontend:
    build: ./frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`stellarstudio.fassih.ch`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=8080"
    volumes:
      - ./frontend:/app:delegated
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
    env_file:
      - .env
    networks:
      - traefik_network

  database:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    networks:
      - traefik_network

  redis:
    image: redis:7-alpine
    user: "1030:1030"
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    networks:
      - traefik_network

volumes:
  grafana-data:
  prometheus-data:
  minio-data:
    driver: local
  frontend_node_modules:
  tmp:
    driver: local

networks:
  traefik_network:
    driver: bridge