global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'

  - job_name: 'celery'
    static_configs:
      - targets: ['celery-exporter:9540']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: minio-job
    bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoibWluaW9hZG1pbiIsImV4cCI6NDg5MjYzMzc0OH0.FTO3O8p_O38YCzDHl2idqFzh1Tzep_Kjc60qBk5oIUvOTHGNX8Ef0jPO7XUXDV3Oi4IXTetYFMroKMllC1psmQ
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
    - targets: ['minio:9000']

  - job_name: 'traefik'
    scrape_interval: 10s
    static_configs:
      - targets: ['traefik:8082']
    metrics_path: '/metrics'

  - job_name: 'mariadb'
    static_configs:
      - targets: ['mariadb-exporter:9104']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
